<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="2" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-11-08T19:46:57 IST" name="Suite" finished-at="2024-11-08T19:47:24 IST" duration-ms="27416">
    <groups>
    </groups>
    <test started-at="2024-11-08T19:46:57 IST" name="Test" finished-at="2024-11-08T19:47:24 IST" duration-ms="27416">
      <class name="com.sd.TestLayer.BuyProductPageTest1">
        <test-method is-config="true" signature="SetUp()[pri:0, instance:com.sd.TestLayer.BuyProductPageTest1@5ffead27]" started-at="2024-11-08T19:46:57 IST" name="SetUp" finished-at="2024-11-08T19:47:03 IST" duration-ms="6049" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method signature="BuyProductFunctinality()[pri:0, instance:com.sd.TestLayer.BuyProductPageTest1@5ffead27]" started-at="2024-11-08T19:47:03 IST" name="BuyProductFunctinality" finished-at="2024-11-08T19:47:09 IST" duration-ms="6004" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BuyProductFunctinality -->
      </class> <!-- com.sd.TestLayer.BuyProductPageTest1 -->
      <class name="com.sd.TestLayer.BuyProductTshirtTest">
        <test-method is-config="true" signature="SetUp()[pri:0, instance:com.sd.TestLayer.BuyProductTshirtTest@36902638]" started-at="2024-11-08T19:47:09 IST" name="SetUp" finished-at="2024-11-08T19:47:10 IST" duration-ms="1773" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method signature="BuyProductFunctinality()[pri:0, instance:com.sd.TestLayer.BuyProductTshirtTest@36902638]" started-at="2024-11-08T19:47:10 IST" name="BuyProductFunctinality" finished-at="2024-11-08T19:47:16 IST" duration-ms="5504" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "org.openqa.selenium.WebElement.click()" because "this.TshirtClick" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebElement.click()" because "this.TshirtClick" is null
at com.sd.PageLayer.BuyProductTshirt.Tshirt(BuyProductTshirt.java:30)
at com.sd.TestLayer.BuyProductTshirtTest.BuyProductFunctinality(BuyProductTshirtTest.java:24)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BuyProductFunctinality -->
      </class> <!-- com.sd.TestLayer.BuyProductTshirtTest -->
      <class name="com.sd.TestLayer.LoginPageTest">
        <test-method is-config="true" signature="SetUp()[pri:0, instance:com.sd.TestLayer.LoginPageTest@223d2c72]" started-at="2024-11-08T19:47:16 IST" name="SetUp" finished-at="2024-11-08T19:47:18 IST" duration-ms="1973" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUp -->
        <test-method signature="verifyLoginWithCorrectCred()[pri:0, instance:com.sd.TestLayer.LoginPageTest@223d2c72]" started-at="2024-11-08T19:47:18 IST" name="verifyLoginWithCorrectCred" finished-at="2024-11-08T19:47:24 IST" duration-ms="5567" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/inventory.htm]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [https://www.saucedemo.com/inventory.html] but found [https://www.saucedemo.com/inventory.htm]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.sd.TestLayer.LoginPageTest.verifyLoginWithCorrectCred(LoginPageTest.java:28)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginWithCorrectCred -->
      </class> <!-- com.sd.TestLayer.LoginPageTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
